using System;
using Content.Shared.GameObjects.Components.Power;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.GameObjects.Components.Power
{
    [GenerateTypedNameReferences]
    public partial class PowerMonitoringWindow : SS14Window, IComputerWindow<PowerMonitoringConsoleBoundInterfaceState>
    {
        public PowerMonitoringWindow()
        {
            RobustXamlLoader.Load(this);
            Title = Loc.GetString("power-monitoring-window-title");
            RequestButton.Text = Loc.GetString("power-monitoring-window-button");
        }
    }

    [UsedImplicitly]
    public class PowerMonitoringConsoleBoundUserInterface : ComputerBoundUserInterface<PowerMonitoringWindow, PowerMonitoringConsoleBoundInterfaceState>
    {
        public PowerMonitoringConsoleBoundUserInterface(ClientUserInterfaceComponent owner, object uiKey) : base(owner, uiKey) {}
    }
}

