- type: entity
  id: CrateSecurityArmor
  name: security armor crate
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - name: OuterclothingHmarmorvest
        amount: 3
      - name: HatHelmet
        amount: 3

- type: entity
  id: CrateSecurityNonlethal
  name: nonlethals crate
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - name: TaserGun
        amount: 3
      - name: StunBaton
        amount: 3
      - name: BoxFlashbang
        amount: 1
      - name: Flash
        amount: 3
#      - Pepperspray
#      - GrenadeTeargas

- type: entity
  id: CrateSecurityLethal
  name: lethals crate
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - name: LaserGun
        amount: 2
      - name: SmgC20r
        amount: 2
      - name: MagazinePistolSmg
        amount: 5
      - name: ShotgunGladstone
        amount: 2
      - name: SmgC20r
        amount: 2
      - name: ShellShotgun
        amount: 12

- type: entity
  id: CrateSecurityRiot
  name: swat crate
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - name: OuterclothingRiot
        amount: 2
      - name: HatLightRiot
        amount: 2
      - name: ShotgunGladstone
        amount: 2
      - name: ShellShotgunBeanbag
        amount: 12
#      - ShieldRiot
#      - SecGasmask

- type: entity
  id: CrateSecuritySupplies
  name: security supplies crate
  parent: CrateSecgear
  components:
  - type: StorageFill
    contents:
      - name: BoxHandcuff
        amount: 1
      - name: BoxSechud
        amount: 1
#      - SecBelt
#      - SecGasmask
#      - SpacelawBook

# Cosmetic Crates
